/**
 * Données de démonstration employees — utilisées quand l'API n'est pas configurée.
 * Le type Employee est celui défini localement dans app/employees/page.tsx.
 */

export const DEMO_DEPARTMENTS_DATA = [
  { id: 1, tenant: 0, organization: 1, parent: null, name: "Ingenierie", code: "ING" },
  { id: 2, tenant: 0, organization: 1, parent: null, name: "Marketing", code: "MKT" },
  { id: 3, tenant: 0, organization: 1, parent: null, name: "Finance", code: "FIN" },
  { id: 4, tenant: 0, organization: 1, parent: null, name: "Ressources Humaines", code: "RH" },
  { id: 5, tenant: 0, organization: 1, parent: null, name: "Commercial", code: "COM" },
  { id: 6, tenant: 0, organization: 1, parent: null, name: "Direction", code: "DIR" },
]

export const DEMO_ORGANIZATIONS_DATA = [
  { id: 1, tenant: 0, name: "SecureCorp HQ", code: "HQ-CASA" },
]

export const DEMO_WORK_SHIFTS_DATA = [
  { id: 1, tenant: 0, name: "Journee Standard", code: "STD", description: "08h00 - 17h00", start_time: "08:00", end_time: "17:00", break_start_time: "12:00", break_end_time: "13:00", overtime_minutes: 0, late_allowable_minutes: 10, early_leave_allowable_minutes: 10, metadata: {} },
  { id: 2, tenant: 0, name: "Quart Matin", code: "MAT", description: "06h00 - 14h00", start_time: "06:00", end_time: "14:00", break_start_time: "10:00", break_end_time: "10:30", overtime_minutes: 0, late_allowable_minutes: 10, early_leave_allowable_minutes: 10, metadata: {} },
  { id: 3, tenant: 0, name: "Quart Soir", code: "SOI", description: "14h00 - 22h00", start_time: "14:00", end_time: "22:00", break_start_time: "18:00", break_end_time: "18:30", overtime_minutes: 0, late_allowable_minutes: 10, early_leave_allowable_minutes: 10, metadata: {} },
]

export const DEMO_ACCESS_GROUPS_DATA = [
  { id: 1, tenant: 0, name: "Acces General", code: "GEN" },
  { id: 2, tenant: 0, name: "Acces Informatique", code: "IT" },
  { id: 3, tenant: 0, name: "Acces Direction", code: "DIR" },
  { id: 4, tenant: 0, name: "Acces Financier", code: "FIN" },
]

export const DEMO_EMPLOYEES_RAW = [
  {
    id: "demo-001",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0001",
    name: "Sarah Chen",
    email: "s.chen@securecorp.fr",
    phone: "+33 6 12 34 56 78",
    departmentId: 1,
    department: "Ingenierie",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Ingenieure Logiciel Senior",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-1234",
    deviceIds: [] as number[],
    accessGroupIds: [1, 2],
    accessGroups: ["Acces General", "Acces Informatique"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 1, template: "" }],
    hireDate: "2021-03-15",
    lastAccess: "09:03:22",
    accessLogs: [
      { id: "al-1", device: "Entree Principale A", status: "granted" as const, timestamp: "09:03:22" },
      { id: "al-2", device: "Salle Serveurs", status: "denied" as const, timestamp: "08:45:10" },
    ],
  },
  {
    id: "demo-002",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0042",
    name: "Michael Torres",
    email: "m.torres@securecorp.fr",
    phone: "+33 6 23 45 67 89",
    departmentId: 2,
    department: "Marketing",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Responsable Marketing Digital",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-2345",
    deviceIds: [] as number[],
    accessGroupIds: [1],
    accessGroups: ["Acces General"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: false },
    fingerprints: [],
    hireDate: "2020-07-01",
    lastAccess: "09:02:58",
    accessLogs: [
      { id: "al-3", device: "Etage 3", status: "granted" as const, timestamp: "09:02:58" },
    ],
  },
  {
    id: "demo-003",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0156",
    name: "Emily Watson",
    email: "e.watson@securecorp.fr",
    phone: "+33 6 34 56 78 90",
    departmentId: 3,
    department: "Finance",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Analyste Financiere",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-3456",
    deviceIds: [] as number[],
    accessGroupIds: [1, 4],
    accessGroups: ["Acces General", "Acces Financier"],
    syncStatus: "pending" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 2, template: "" }],
    hireDate: "2022-01-10",
    lastAccess: "09:02:31",
    accessLogs: [
      { id: "al-4", device: "Salle Finance", status: "granted" as const, timestamp: "09:02:31" },
    ],
  },
  {
    id: "demo-004",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0089",
    name: "James Liu",
    email: "j.liu@securecorp.fr",
    phone: "+33 6 45 67 89 01",
    departmentId: 1,
    department: "Ingenierie",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Architecte Infrastructure",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-4567",
    deviceIds: [] as number[],
    accessGroupIds: [1, 2],
    accessGroups: ["Acces General", "Acces Informatique"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 1, template: "" }, { fingerIndex: 2, template: "" }],
    hireDate: "2019-11-20",
    lastAccess: "09:01:45",
    accessLogs: [
      { id: "al-5", device: "Entree Principale B", status: "granted" as const, timestamp: "09:01:45" },
    ],
  },
  {
    id: "demo-005",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0203",
    name: "Anna Kowalski",
    email: "a.kowalski@securecorp.fr",
    phone: "+33 6 56 78 90 12",
    departmentId: 4,
    department: "Ressources Humaines",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Responsable RH",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-5678",
    deviceIds: [] as number[],
    accessGroupIds: [1],
    accessGroups: ["Acces General"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: false },
    fingerprints: [],
    hireDate: "2018-04-05",
    lastAccess: "09:00:12",
    accessLogs: [
      { id: "al-6", device: "Bureau RH", status: "granted" as const, timestamp: "09:00:12" },
    ],
  },
  {
    id: "demo-006",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0078",
    name: "David Kim",
    email: "d.kim@securecorp.fr",
    phone: "+33 6 67 89 01 23",
    departmentId: 5,
    department: "Commercial",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Directeur Commercial",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-6789",
    deviceIds: [] as number[],
    accessGroupIds: [1, 3],
    accessGroups: ["Acces General", "Acces Direction"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 1, template: "" }],
    hireDate: "2017-09-12",
    lastAccess: "08:59:33",
    accessLogs: [
      { id: "al-7", device: "Entree Principale A", status: "granted" as const, timestamp: "08:59:33" },
    ],
  },
  {
    id: "demo-007",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0112",
    name: "Rachel Green",
    email: "r.green@securecorp.fr",
    phone: "+33 6 78 90 12 34",
    departmentId: 1,
    department: "Ingenierie",
    organizationId: 1,
    workShiftId: 2,
    workShift: "Quart Matin",
    workShiftIds: [2],
    workShifts: ["Quart Matin"],
    position: "Designer UX/UI",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-7890",
    deviceIds: [] as number[],
    accessGroupIds: [1],
    accessGroups: ["Acces General"],
    syncStatus: "pending" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: false },
    fingerprints: [],
    hireDate: "2023-02-01",
    lastAccess: "08:58:17",
    accessLogs: [
      { id: "al-8", device: "Lab Creatif", status: "granted" as const, timestamp: "08:58:17" },
    ],
  },
  {
    id: "demo-008",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0199",
    name: "Marc Dupont",
    email: "m.dupont@securecorp.fr",
    phone: "+33 6 89 01 23 45",
    departmentId: 6,
    department: "Direction",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Directeur General",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-8901",
    deviceIds: [] as number[],
    accessGroupIds: [1, 2, 3, 4],
    accessGroups: ["Acces General", "Acces Informatique", "Acces Direction", "Acces Financier"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 1, template: "" }, { fingerIndex: 2, template: "" }],
    hireDate: "2015-06-01",
    lastAccess: "08:55:00",
    accessLogs: [
      { id: "al-9", device: "Entree Direction", status: "granted" as const, timestamp: "08:55:00" },
    ],
  },
  {
    id: "demo-009",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0234",
    name: "Leila Benali",
    email: "l.benali@securecorp.fr",
    phone: "+33 6 90 12 34 56",
    departmentId: 3,
    department: "Finance",
    organizationId: 1,
    workShiftId: 1,
    workShift: "Journee Standard",
    workShiftIds: [1],
    workShifts: ["Journee Standard"],
    position: "Comptable Senior",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-9012",
    deviceIds: [] as number[],
    accessGroupIds: [1, 4],
    accessGroups: ["Acces General", "Acces Financier"],
    syncStatus: "synced" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: true },
    fingerprints: [{ fingerIndex: 1, template: "" }],
    hireDate: "2020-10-15",
    lastAccess: "09:10:05",
    accessLogs: [
      { id: "al-10", device: "Salle Finance", status: "granted" as const, timestamp: "09:10:05" },
    ],
  },
  {
    id: "demo-010",
    apiId: null as null,
    tenantId: null as null,
    employeeId: "EMP-0301",
    name: "Thomas Moreau",
    email: "t.moreau@securecorp.fr",
    phone: "+33 6 01 23 45 67",
    departmentId: 2,
    department: "Marketing",
    organizationId: 1,
    workShiftId: 3,
    workShift: "Quart Soir",
    workShiftIds: [3],
    workShifts: ["Quart Soir"],
    position: "Charge de Communication",
    photoUrl: "",
    faceData: "",
    cardNumber: "4789-0123",
    deviceIds: [] as number[],
    accessGroupIds: [1],
    accessGroups: ["Acces General"],
    syncStatus: "pending" as const,
    biometricStatus: { hasFacePhoto: false, hasFingerprint: false },
    fingerprints: [],
    hireDate: "2024-01-08",
    lastAccess: "14:02:33",
    accessLogs: [
      { id: "al-11", device: "Entree Principale A", status: "granted" as const, timestamp: "14:02:33" },
    ],
  },
]
