export type AlertSeverity = "critical" | "high" | "medium" | "low" | "info"
export type AlertStatus = "active" | "acknowledged" | "resolved" | "dismissed"
export type AlertCategory = "access" | "intrusion" | "device" | "system" | "compliance"
export type AlertObject = { id: string; title: string; description: string; severity: AlertSeverity; status: AlertStatus; category: AlertCategory; location: string; zoneId: string; source: string; createdAt: string; updatedAt: string; acknowledgedBy?: string; resolvedBy?: string; resolvedAt?: string; eventCount: number; tags: string[] }
export type IncidentStatus = "open" | "investigating" | "contained" | "resolved" | "closed"
export type IncidentSeverity = "P1" | "P2" | "P3" | "P4"
export type IncidentEvent = { id: string; type: "comment" | "status_change" | "assignment" | "action" | "escalation"; author: string; content: string; createdAt: string }
export type Incident = { id: string; title: string; description: string; severity: IncidentSeverity; status: IncidentStatus; category: AlertCategory; location: string; assignedTo: string; createdAt: string; updatedAt: string; resolvedAt?: string; affectedAssets: string[]; relatedAlerts: string[]; timeline: IncidentEvent[]; sla: string }
export type AlertRule = { id: string; name: string; description: string; severity: AlertSeverity; category: AlertCategory; enabled: boolean; conditions: string; actions: string[]; cooldownMinutes: number; triggeredCount: number; lastTriggered?: string; createdAt: string }
export const ALERTS: AlertObject[] = []
export const INCIDENTS: Incident[] = []
export const ALERT_RULES: AlertRule[] = []
export const ALERT_STATS = { active: 0, acknowledged: 0, resolved24h: 0, critical: 0, mttrMinutes: 0 }
