export type IntegrationStatus = "active" | "inactive" | "error" | "pending" | "deprecated"
export type SyncStatus = "success" | "failed" | "partial" | "running" | "pending"
export type Integration = { id: string; name: string; provider: string; category: string; status: IntegrationStatus; description?: string }
export type Webhook = { id: string; name: string; url: string; active: boolean; events: string[] }
export type ApiKey = { id: string; name: string; keyPreview: string; scopes: string[]; createdAt: string; lastUsedAt?: string; status: "active" | "revoked" }
export type SyncLog = { id: string; integrationId: string; status: SyncStatus; startedAt: string; finishedAt?: string; message?: string }
export const INTEGRATIONS: Integration[] = []
export const WEBHOOKS: Webhook[] = []
export const API_KEYS: ApiKey[] = []
export const SYNC_LOGS: SyncLog[] = []
export const INTEGRATION_STATS = { total: 0, active: 0, warnings: 0, errors24h: 0 }
