/**
 * Données de démonstration pour la page Appareils.
 * Utilisées quand l'API n'est pas disponible.
 */

export const DEMO_DEVICES_DATA = [
  {
    id: "demo-dev-001",
    devIndex: "DEV-001",
    coreDeviceId: undefined as number | undefined,
    name: "Entree Principale A",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-001",
    location: "Batiment A, Rez-de-chaussee",
    ipAddress: "192.168.1.101",
    macAddress: "AA:BB:CC:DD:00:01",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 87,
    todayEvents: 142,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-002",
    devIndex: "DEV-002",
    coreDeviceId: undefined as number | undefined,
    name: "Entree Principale B",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-002",
    location: "Batiment A, Rez-de-chaussee",
    ipAddress: "192.168.1.102",
    macAddress: "AA:BB:CC:DD:00:02",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 65,
    todayEvents: 98,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-003",
    devIndex: "DEV-003",
    coreDeviceId: undefined as number | undefined,
    name: "Etage 2 - Acces",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-003",
    location: "Batiment A, Etage 2",
    ipAddress: "192.168.1.103",
    macAddress: "AA:BB:CC:DD:00:03",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 43,
    todayEvents: 67,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-004",
    devIndex: "DEV-004",
    coreDeviceId: undefined as number | undefined,
    name: "Etage 3 - Acces",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-004",
    location: "Batiment A, Etage 3",
    ipAddress: "192.168.1.104",
    macAddress: "AA:BB:CC:DD:00:04",
    status: "online" as const,
    lastSeen: "Il y a 1 min",
    firmware: "V2.2.4",
    connectedUsers: 34,
    todayEvents: 52,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-005",
    devIndex: "DEV-005",
    coreDeviceId: undefined as number | undefined,
    name: "Salle Serveurs",
    type: "reader" as const,
    model: "DS-K1T804AMF",
    serialNumber: "SN-20231001-005",
    location: "Batiment B, Sous-sol",
    ipAddress: "192.168.1.105",
    macAddress: "AA:BB:CC:DD:00:05",
    status: "warning" as const,
    lastSeen: "Il y a 4 min",
    firmware: "V2.1.9",
    connectedUsers: 12,
    todayEvents: 18,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-006",
    devIndex: "DEV-006",
    coreDeviceId: undefined as number | undefined,
    name: "Bureau RH",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-006",
    location: "Batiment A, Etage 4",
    ipAddress: "192.168.1.106",
    macAddress: "AA:BB:CC:DD:00:06",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 8,
    todayEvents: 22,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-007",
    devIndex: "DEV-007",
    coreDeviceId: undefined as number | undefined,
    name: "Lab Creatif",
    type: "door_controller" as const,
    model: "DS-K1T671TM",
    serialNumber: "SN-20231001-007",
    location: "Batiment C, Etage 1",
    ipAddress: "192.168.1.107",
    macAddress: "AA:BB:CC:DD:00:07",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 21,
    todayEvents: 41,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-008",
    devIndex: "DEV-008",
    coreDeviceId: undefined as number | undefined,
    name: "Parking - Barriere",
    type: "turnstile" as const,
    model: "DS-K3B501TM",
    serialNumber: "SN-20231001-008",
    location: "Parking Exterieur",
    ipAddress: "192.168.1.108",
    macAddress: "AA:BB:CC:DD:00:08",
    status: "offline" as const,
    lastSeen: "Il y a 2h 15min",
    firmware: "V1.3.2",
    connectedUsers: 0,
    todayEvents: 7,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-009",
    devIndex: "DEV-009",
    coreDeviceId: undefined as number | undefined,
    name: "Entree Direction",
    type: "fingerprint" as const,
    model: "DS-K1T671TM-F",
    serialNumber: "SN-20231001-009",
    location: "Batiment A, Etage 5",
    ipAddress: "192.168.1.109",
    macAddress: "AA:BB:CC:DD:00:09",
    status: "online" as const,
    lastSeen: "A l'instant",
    firmware: "V2.2.4",
    connectedUsers: 5,
    todayEvents: 12,
    tenantCode: "HQ-CASA",
  },
  {
    id: "demo-dev-010",
    devIndex: "DEV-010",
    coreDeviceId: undefined as number | undefined,
    name: "Cafeteria",
    type: "reader" as const,
    model: "DS-K1102M",
    serialNumber: "SN-20231001-010",
    location: "Batiment A, RDC",
    ipAddress: "192.168.1.110",
    macAddress: "AA:BB:CC:DD:00:10",
    status: "warning" as const,
    lastSeen: "Il y a 8 min",
    firmware: "V1.8.6",
    connectedUsers: 0,
    todayEvents: 0,
    tenantCode: "HQ-CASA",
  },
]
