export type FloorId = string
export type Camera = { id: string; name: string; floorId: FloorId; status: "online" | "offline" | "warning"; streamUrl?: string }
export type Door = { id: string; name: string; floorId: FloorId; status: "open" | "closed" | "forced" }
export type LiveEvent = { id: string; type: string; message: string; createdAt: string }
export type ZoneOverview = { id: string; name: string; risk: "low" | "medium" | "high"; activeAlerts: number }
export const FLOORS: Array<{ id: FloorId; label: string; shortLabel: string }> = []
export const CAMERAS: Camera[] = []
export const DOORS: Door[] = []
export const LIVE_EVENTS: LiveEvent[] = []
export const ZONE_OVERVIEW: ZoneOverview[] = []
export const SURVEILLANCE_STATS = { onlineCameras: 0, offlineCameras: 0, openDoors: 0, activeIncidents: 0 }
