import type {
  AccessEvent,
  DashboardKPIData,
  Device,
  PriorityAction,
} from "@/components/dashboard/types"

export const dashboardKpiData: DashboardKPIData = {
  presentToday: { count: 234, total: 256 },
  totalAbsences: 18,
  lateArrivals: 7,
  activeDevices: { count: 12, total: 12 },
}

export const accessEvents: AccessEvent[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    name: "Sarah Chen",
    department: "Engineering",
    deviceName: "Main Entrance A",
    status: "granted",
    timestamp: "09:03:22",
  },
  {
    id: "2",
    employeeId: "EMP-042",
    name: "Michael Torres",
    department: "Marketing",
    deviceName: "Floor 3 Access",
    status: "granted",
    timestamp: "09:02:58",
  },
  {
    id: "3",
    employeeId: "EMP-156",
    name: "Emily Watson",
    department: "Finance",
    deviceName: "Server Room",
    status: "denied",
    timestamp: "09:02:31",
  },
  {
    id: "4",
    employeeId: "EMP-089",
    name: "James Liu",
    department: "Engineering",
    deviceName: "Main Entrance B",
    status: "granted",
    timestamp: "09:01:45",
  },
  {
    id: "5",
    employeeId: "EMP-203",
    name: "Anna Kowalski",
    department: "HR",
    deviceName: "HR Office",
    status: "granted",
    timestamp: "09:00:12",
  },
  {
    id: "6",
    employeeId: "EMP-078",
    name: "David Kim",
    department: "Sales",
    deviceName: "Main Entrance A",
    status: "granted",
    timestamp: "08:59:33",
  },
  {
    id: "7",
    employeeId: "EMP-112",
    name: "Rachel Green",
    department: "Design",
    deviceName: "Creative Lab",
    status: "granted",
    timestamp: "08:58:17",
  },
]

export const devices: Device[] = [
  {
    id: "dev-001",
    name: "Main Entrance A",
    type: "door_controller",
    location: "Building A, Ground Floor",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-002",
    name: "Main Entrance B",
    type: "door_controller",
    location: "Building A, Ground Floor",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-003",
    name: "Floor 2 Access",
    type: "door_controller",
    location: "Building A, Floor 2",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-004",
    name: "Floor 3 Access",
    type: "door_controller",
    location: "Building A, Floor 3",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-005",
    name: "Server Room",
    type: "reader",
    location: "Building B, Basement",
    status: "warning",
    lastSeen: "2 min ago",
  },
  {
    id: "dev-006",
    name: "HR Office",
    type: "door_controller",
    location: "Building A, Floor 4",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-007",
    name: "Creative Lab",
    type: "door_controller",
    location: "Building C, Floor 1",
    status: "online",
    lastSeen: "Just now",
  },
  {
    id: "dev-008",
    name: "Parking Gate",
    type: "turnstile",
    location: "Parking Lot",
    status: "online",
    lastSeen: "Just now",
  },
]

export const priorityActions: PriorityAction[] = [
  {
    id: "critical-webhook",
    title: "Webhook a verifier",
    description: "Des notifications d'evenements ACS n'ont pas ete confirmees.",
    priority: "critical",
    count: 3,
    ctaLabel: "Diagnostiquer",
    ctaHref: "/settings",
  },
  {
    id: "warning-devices",
    title: "Appareils hors service",
    description: "Certains lecteurs ne remontent plus de telemetrie depuis plus de 10 minutes.",
    priority: "warning",
    count: 2,
    ctaLabel: "Voir les appareils",
    ctaHref: "/devices",
  },
  {
    id: "warning-pending-push",
    title: "Push employes en attente",
    description: "Des employes restent non synchronises sur les lecteurs assignes.",
    priority: "warning",
    count: 8,
    ctaLabel: "Traiter la file",
    ctaHref: "/employees",
  },
  {
    id: "info-corrections",
    title: "Corrections de pointage",
    description: "Des corrections RH attendent une validation operationnelle.",
    priority: "info",
    count: 5,
    ctaLabel: "Valider",
    ctaHref: "/reports",
  },
]
